name: Check if install.py runs without errors
on: [push, pull_request]
jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Setup dependencies
        run: pip install requests
      - name: Install
        run: install.py
  Windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Setup dependencies
        run: pip install requests
      - name: Install
        run: install.py
  macOS:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Setup dependencies
        run: pip install requests
      - name: Install
        run: install.py
